DuckTracker/Models/ErrorViewModel.cs
using System;

namespace DuckTracker.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DuckTracker/Controllers/DuckPageController.cs
using DuckTracker.Data;
using DuckTracker.Data.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace DuckTracker.Controllers
{
    public class DuckPageController : Controller
    {

        private readonly DuckContext _context;
        //private DuckContext Context;
        public DuckPageController(DuckContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var ducksList = _context.Set<Duck>().ToList();

            return View(ducksList);
        }

        public IActionResult AddDuck(string Name, string Location)
        {
            return View();
        }

        [HttpPost]
        [ActionName("addDuck")]

        public IActionResult AddDuck_Post([Bind("Name,Location,Details")] Duck duck)
        {
            if (ModelState.IsValid)
            {
                var duckNameCheck = _context.Set<Duck>().Where(d => d.Name == duck.Name && d.Id != duck.Id).FirstOrDefault();

                if (duckNameCheck == null)
                {
                    //do stuff
                    _context.Set<Duck>().Add(duck);
                    _context.SaveChanges();
                }
                else
                {
                    ModelState.AddModelError("Name", "A duck with this name already exists.");
                    return View(duck);
                }
            }


            return RedirectToAction("Index");
        }


         
    }
}

DuckTracker/Controllers/HomeController.cs
using DuckTracker.Data;
using DuckTracker.Data.Entities;
using DuckTracker.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Linq;

namespace DuckTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DuckContext _context;

        public HomeController(ILogger<HomeController> logger, DuckContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            
            var ducksList = _context.Set<Duck>().ToList();

            return View(ducksList);
        }



        public IActionResult Edit(int id)
        {
            // get from database by id
            var editDuck = _context.Set<Duck>().Where(d => d.Id == id).FirstOrDefault();
            return View(editDuck);
        }

        [HttpPost]
        [ActionName("Edit")]
        public IActionResult Edit_Post([Bind("Id,Name,Location,Details")] Duck duck)
        {
            // editing
            if (ModelState.IsValid)
            {
                var duckNameCheck = _context.Set<Duck>().Where(d => d.Name == duck.Name && d.Id != duck.Id).FirstOrDefault();

                if(duckNameCheck == null)
                {
                    //do stuff
                    _context.Set<Duck>().Update(duck);
                    _context.SaveChanges();
                } 
                else
                {
                    ModelState.AddModelError("Name", "A duck with this name already exists.");
                    return View(duck);
                }
            }
         

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var delDuck = _context.Set<Duck>().Where(d => d.Id == id).FirstOrDefault();
            return View(delDuck);
        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult Delete_Post([Bind("Id,Name,Location,Details")] Duck duck)
        {
            if (ModelState.IsValid)
            {
                var duckNameCheck = _context.Set<Duck>().Where(d => d.Name == duck.Name && d.Id != duck.Id).FirstOrDefault();
                
                if (duckNameCheck == null)
                {
                    _context.Set<Duck>().Remove(duck);
                    _context.SaveChanges();
                } 
                else
                {
                    ModelState.AddModelError("Name", "A duck with the same name exists.");
                    return View(duck);
                }
            }

            return RedirectToAction("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DuckTracker/Views/DuckPage/AddDuck.cshtml
@model DuckTracker.Data.Entities.Duck
@using DuckTracker.Data.Entities

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Found a Duck? Add them here!</h1>
<div class="row justify-content-center">
    <div class="col-auto">
        <form asp-action="addDuck" class="jumbotron" style="color: white; background-color: rgba(0,0,0,.4)">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input class="form-control" type="text" asp-for="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Location">Location</label>
                <input class="form-control" type="text" asp-for="Location" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details">Details</label>
                <input class="form-control" type="text" asp-for="Details" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <input class="btn btn-primary" type="submit" />
            <a asp-controller="DuckPage" asp-action="Index" class="btn btn-primary">Cancel</a>
        </form>
    </div>
</div>

DuckTracker/Views/DuckPage/Index.cshtml
@model IEnumerable<DuckTracker.Data.Entities.Duck>
@using DuckTracker.Data.Entities

@{
    ViewData["Title"] = "Ducks";
}

<div class="text-center">
    <h1 class="display-4">DUCKS!</h1>
    <p>Add all the ducks you can find! This will also tell you where to find some ducks!</p>
</div>

<div class="row justify-content-center">
    <div class="col-auto">
        <table class="table table-responsive jumbotron" style="color: white; background-color: rgba(0,0,0,.4)">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Location)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Details)
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Location)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Details)
                        </td>
                        <td class="btn-group-sm">
                            <a class="btn-sm btn-outline-primary" style="color: white" asp-controller="Home" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a class="btn-sm btn-outline-danger" style="color: white" asp-controller="Home" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
                <tr>
                    <td>
                        <a asp-action="AddDuck" class="btn btn-primary">Add a duck!</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

DuckTracker/Views/Home/Delete.cshtml
@model DuckTracker.Data.Entities.Duck
@using DuckTracker.Data.Entities
@{
    ViewData["Title"] = "Delete";
}


<h1 class="text-center">Are you sure you want to delete @Model.Name?</h1>

<div class="row justify-content-center">
    <div class="col-auto">
        <form asp-action="Delete" class="jumbotron" style="color: white; background-color: rgba(0,0,0,.4)">
            @Html.ValidationSummary(false)
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input class="form-control" asp-for="Name" readonly />
            </div>
            <div class="form-group">
                <label asp-for="Location">Location</label>
                <input class="form-control" asp-for="Location" readonly />
            </div>
            <div class="form-group">
                <label asp-for="Details">Details</label>
                <input class="form-control" type="text" asp-for="Details" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <!--<p class="font-weight-bold">@Model.Name the duck</p>-->
            <!--<p class="font-weight-bold">@Model.Location</p>-->

            <input class="btn btn-danger" type="submit" value="Delete @Model.Name" />
            <a asp-action="Index" class="btn btn-primary">Cancel</a>
        </form>
    </div>
</div>

DuckTracker/Views/Home/Edit.cshtml
@model DuckTracker.Data.Entities.Duck
@using DuckTracker.Data.Entities

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">@Model.Name</h1> 
<div class="row justify-content-center">
    <div class="col-auto">
        <form asp-action="Edit" class="jumbotron" style="color: white; background-color: rgba(0,0,0,.4)">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name">Name</label>
                <input class="form-control" type="text" asp-for="Name" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Location">Location</label>
                <input class="form-control" type="text" asp-for="Location" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details">Details</label>
                <input class="form-control" type="text" asp-for="Details" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <input class="btn btn-primary" type="submit" />
            <a asp-action="Index" class="btn btn-primary">Cancel</a>
        </form>
    </div>
</div>

DuckTracker/Views/Home/Index.cshtml
@model IEnumerable<DuckTracker.Data.Entities.Duck>
@using DuckTracker.Data.Entities

@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center">
    <h1 class="display-4">Welcome to Duck Tracker</h1>
    <p>This webapp will track all the ducks around the offce. You can also input new ducks you find!.</p>
</div>

<div class="row justify-content-center">
    <div class="col-auto" >
        <table class="table table-responsive jumbotron" style="color: white; background-color: rgba(0,0,0,.4)">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Location)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Details)
                    </th>
                    <!--<th>
        Action
    </th>-->
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Details)
                    </td>
                    <!--<td class="btn-group-sm">
        <a class="btn-sm btn-outline-primary" style="color: white" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
        <a class="btn-sm btn-outline-danger" style="color: white" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
    </td>-->

                </tr>
                }
                <tr>
                    <td>
                        <a asp-controller="DuckPage" asp-action="AddDuck" class="btn btn-primary">Add a duck!</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

DuckTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DuckTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body style="background-image: url(https://wallpaperaccess.com/full/1392039.jpg); color: black; background-blend-mode: multiply ">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: navajowhite">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DuckTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--<li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </li>-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DuckPage" asp-action="Index">DUCKS!</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted" style="background-color: navajowhite">
        <div class="container">
            &copy; 2021 - DuckTracker <!-- - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>-->
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>